import { Card } from './types'

export const CARDS: Card[] = [
  // ── A 类：新移民专属 ────────────────────────────────────────────
  {
    id: 'scotiabank-scene-newcomer',
    nameEn: 'Scotiabank Scene+ Visa',
    nameZh: '丰业银行 Scene+ Visa（新移民版）',
    annualFee: 0,
    network: 'Visa',
    issuer: 'Scotiabank',
    minIncome: 0,
    requiresCreditHistory: false,
    newcomerProgram: true,
    rewards: { groceries: 3, base: 1.5 },
    noForeignFee: false,
    sobeysBonus: true,
    category: 'newcomer',
    highlights: [
      '无需加拿大信用记录，新移民直接申请',
      'Sobeys / IGA / FreshCo / Safeway 超市消费 3 倍积分',
      '积分可换 Cineplex 电影票或礼品卡',
    ],
    applyUrl: 'https://www.scotiabank.com/ca/en/personal/credit-cards/visa/scene-card.html',
  },
  {
    id: 'rbc-visa-classic-newcomer',
    nameEn: 'RBC Visa Classic (Newcomer)',
    nameZh: 'RBC Visa 经典卡（新移民项目）',
    annualFee: 0,
    network: 'Visa',
    issuer: 'RBC',
    minIncome: 0,
    requiresCreditHistory: false,
    newcomerProgram: true,
    rewards: { base: 1 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'newcomer',
    highlights: [
      '无需加拿大信用历史，RBC 快速审批',
      '零年费帮你起步建立信用',
      'RBC 华人分支多，中文服务方便',
    ],
    applyUrl: 'https://www.rbc.com/newcomers/credit-cards-for-newcomers.html',
  },
  {
    id: 'bmo-newcomer-no-fee',
    nameEn: 'BMO Newcomer No-Fee Mastercard',
    nameZh: 'BMO 新移民免年费 Mastercard',
    annualFee: 0,
    network: 'Mastercard',
    issuer: 'BMO',
    minIncome: 0,
    requiresCreditHistory: false,
    newcomerProgram: true,
    rewards: { groceries: 3, bills: 1, housing: 1, base: 0.5 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'newcomer',
    highlights: [
      '无需加拿大信用记录',
      '超市 3% 现金返还，Mastercard 网络 Costco 可用',
      '无年费，零风险起步',
    ],
    applyUrl: 'https://www.bmo.com/en-ca/main/personal/credit-cards/newcomers-to-canada/',
  },
  {
    id: 'cibc-smart-newcomer',
    nameEn: 'CIBC Smart for Newcomers',
    nameZh: 'CIBC 新移民智能卡',
    annualFee: 0,
    network: 'Visa',
    issuer: 'CIBC',
    minIncome: 0,
    requiresCreditHistory: false,
    newcomerProgram: true,
    rewards: { base: 1 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'newcomer',
    highlights: [
      '无需加拿大信用记录',
      'CIBC 华人分支广覆盖',
      '无年费，适合学生或刚到加拿大',
    ],
    applyUrl: 'https://www.cibc.com/en/journeys/banking-offers-for-newcomers/newcomer-credit-cards.html',
  },

  // ── B 类：无年费日常卡 ───────────────────────────────────────────
  {
    id: 'tangerine-money-back',
    nameEn: 'Tangerine Money-Back World Mastercard',
    nameZh: 'Tangerine 现金返还 World Mastercard',
    annualFee: 0,
    network: 'Mastercard',
    issuer: 'Tangerine',
    minIncome: 0,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { groceries: 2, dining: 2, gas: 2, shopping: 2, bills: 2, housing: 2, base: 0.5 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'no-fee',
    highlights: [
      '可自定义 2–3 个 2% 返现类别，灵活性最高',
      '房租 / 房贷支出也可选为 2% 类别',
      'Mastercard 网络，Costco 可用',
    ],
    applyUrl: 'https://www.tangerine.ca/en/personal/spend/credit-cards/money-back-credit-card',
  },
  {
    id: 'rogers-red-world-elite',
    nameEn: 'Rogers Red World Elite Mastercard',
    nameZh: 'Rogers 世界精英 Mastercard',
    annualFee: 0,
    network: 'Mastercard',
    issuer: 'Rogers Bank',
    minIncome: 12000,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { shopping: 3, base: 1.5 },
    noForeignFee: true,
    sobeysBonus: false,
    category: 'no-fee',
    highlights: [
      '无外币手续费，海淘 / 回国购物零损耗',
      '所有消费 1.5% 返现，Rogers 客户 2%',
      '无年费 Mastercard，Costco 可用',
    ],
    applyUrl: 'https://www.rogersbank.com/en/rogers_red_worldelite_mastercard_details/',
  },
  {
    id: 'home-trust-preferred',
    nameEn: 'Home Trust Preferred Visa',
    nameZh: 'Home Trust Preferred Visa',
    annualFee: 0,
    network: 'Visa',
    issuer: 'Home Trust',
    minIncome: 0,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { base: 1 },
    noForeignFee: true,
    sobeysBonus: false,
    category: 'no-fee',
    highlights: [
      '无外币手续费，海外 / 海淘消费不多付 2.5%',
      '无年费，海淘族首选副卡',
      'Visa 网络接受度广',
    ],
    applyUrl: 'https://www.hometrust.ca/credit-cards/preferred-visa-card/',
  },
  {
    id: 'bmo-cashback-no-fee',
    nameEn: 'BMO CashBack Mastercard',
    nameZh: 'BMO 现金返还 Mastercard（无年费版）',
    annualFee: 0,
    network: 'Mastercard',
    issuer: 'BMO',
    minIncome: 0,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { groceries: 3, base: 0.5 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'no-fee',
    highlights: [
      '无年费超市 3% 返现，任何超市均适用',
      '学生 / 建立信用初期最佳选择',
      'Mastercard，Costco 可用',
    ],
    applyUrl: 'https://www.bmo.com/main/personal/credit-cards/bmo-cashback-mastercard/',
  },

  // ── C 类：现金返还（有年费） ─────────────────────────────────────
  {
    id: 'td-cash-back-infinite',
    nameEn: 'TD Cash Back Visa Infinite',
    nameZh: 'TD 现金返还 Visa Infinite',
    annualFee: 139,
    network: 'Visa',
    issuer: 'TD',
    minIncome: 60000,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { groceries: 3, dining: 3, bills: 3, gas: 3, base: 1 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'cashback',
    highlights: [
      '超市 + 餐厅 + 加油同时 3% 返现，任何超市均适用',
      'TD 用户最顺手，配套保险全面',
      '首年通常免年费',
    ],
    applyUrl: 'https://www.td.com/ca/en/personal-banking/products/credit-cards/cash-back/cash-back-visa-infinite-card/',
  },
  {
    id: 'bmo-cashback-world-elite',
    nameEn: 'BMO CashBack World Elite Mastercard',
    nameZh: 'BMO 现金返还世界精英 Mastercard',
    annualFee: 120,
    network: 'Mastercard',
    issuer: 'BMO',
    minIncome: 80000,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { groceries: 5, bills: 2, gas: 3, housing: 2, base: 1 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'cashback',
    highlights: [
      '超市 5%，Costco 可用，加拿大最高返现率',
      'BMO 高级账户客户可免年费',
      'DragonPass 机场贵宾室',
    ],
    applyUrl: 'https://www.bmo.com/en-ca/main/personal/credit-cards/bmo-cashback-world-elite-mastercard/',
  },
  {
    id: 'amex-simplycash-preferred',
    nameEn: 'Amex SimplyCash Preferred',
    nameZh: '美国运通 SimplyCash 优选卡',
    annualFee: 120,
    network: 'Amex',
    issuer: 'American Express',
    minIncome: 0,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { groceries: 4, gas: 4, base: 2 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'cashback',
    highlights: [
      '所有消费保底 2%，全类别最高返现',
      '加油 + 超市 4%，无收入要求',
      '注意：Costco 不接受 Amex',
    ],
    applyUrl: 'https://www.americanexpress.com/en-ca/credit-cards/simply-cash-preferred/',
  },
  {
    id: 'cibc-dividend-infinite',
    nameEn: 'CIBC Dividend Visa Infinite',
    nameZh: 'CIBC Dividend Visa Infinite',
    annualFee: 120,
    network: 'Visa',
    issuer: 'CIBC',
    minIncome: 60000,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { groceries: 4, dining: 4, gas: 4, base: 1 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'cashback',
    highlights: [
      '超市 + 餐厅 + 加油同时 4% 返现，任何超市均适用',
      'CIBC 客户体验顺畅',
      '日常全面消费覆盖',
    ],
    applyUrl: 'https://www.cibc.com/en/personal-banking/credit-cards/all-credit-cards/dividend-visa-infinite-card.html',
  },
  {
    id: 'scotia-momentum-infinite',
    nameEn: 'Scotia Momentum Visa Infinite',
    nameZh: '丰业银行 Momentum Visa Infinite',
    annualFee: 120,
    network: 'Visa',
    issuer: 'Scotiabank',
    minIncome: 60000,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { groceries: 4, dining: 4, bills: 2, housing: 2, base: 1 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'cashback',
    highlights: [
      '超市 + 餐厅 4%，药店也 4%，任何超市均适用',
      '账单 / 房租类 2%，覆盖面广',
      'Scotiabank 用户首选现金卡',
    ],
    applyUrl: 'https://www.scotiabank.com/ca/en/personal/credit-cards/visa/momentum-infinite-card.html',
  },

  // ── D 类：旅行积分 ───────────────────────────────────────────────
  {
    id: 'amex-cobalt',
    nameEn: 'American Express Cobalt Card',
    nameZh: '美国运通 Cobalt 卡',
    annualFee: 155,
    network: 'Amex',
    issuer: 'American Express',
    minIncome: 0,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { groceries: 5, dining: 5, travel: 2, base: 1 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'travel',
    highlights: [
      '连续 8 年加拿大最佳信用卡',
      '餐厅 / 外卖 / 超市 5 倍积分，月限 $2500（注意：Costco 不接受 Amex）',
      '积分换 Air Canada 机票最划算',
    ],
    applyUrl: 'https://www.americanexpress.com/en-ca/credit-cards/cobalt-card/',
  },
  {
    id: 'scotia-gold-amex',
    nameEn: 'Scotiabank Gold American Express',
    nameZh: '丰业银行 Gold Amex',
    annualFee: 120,
    network: 'Amex',
    issuer: 'Scotiabank',
    minIncome: 0,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { groceries: 5, dining: 5, gas: 3, bills: 3, housing: 3, base: 1 },
    noForeignFee: true,
    sobeysBonus: true,
    category: 'travel',
    highlights: [
      '无外币手续费，回国 / 海淘不亏 2.5%',
      '餐厅 + 超市 5 倍，Sobeys / IGA / Safeway 享额外优惠（注意：Costco 不接受 Amex）',
      'Scene+ 积分可换电影票 / 礼品卡 / 旅行',
    ],
    applyUrl: 'https://www.scotiabank.com/ca/en/personal/credit-cards/american-express/gold-card.html',
  },
  {
    id: 'td-first-class-travel',
    nameEn: 'TD First Class Travel Visa Infinite',
    nameZh: 'TD 头等舱旅行 Visa Infinite',
    annualFee: 139,
    network: 'Visa',
    issuer: 'TD',
    minIncome: 60000,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { travel: 8, base: 3 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'travel',
    highlights: [
      'Expedia for TD 订机票 8 倍积分，回国最划算',
      '旅行保险配套完整，延误险医疗险都有',
      'TD 华人用户基础最大',
    ],
    applyUrl: 'https://www.td.com/ca/en/personal-banking/products/credit-cards/travel-rewards/first-class-travel-visa-infinite-card',
  },
  {
    id: 'scotia-passport-infinite',
    nameEn: 'Scotiabank Passport Visa Infinite',
    nameZh: '丰业银行 Passport Visa Infinite',
    annualFee: 150,
    network: 'Visa',
    issuer: 'Scotiabank',
    minIncome: 60000,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { groceries: 3, dining: 3, base: 1 },
    noForeignFee: true,
    sobeysBonus: false,
    category: 'travel',
    highlights: [
      '无外币手续费 + 6 次免费机场贵宾室',
      '全面旅行保险，出行最完整套餐',
      'Scene+ 积分灵活可换多种奖励',
    ],
    applyUrl: 'https://www.scotiabank.com/ca/en/personal/credit-cards/visa/passport-infinite-card.html',
  },
  {
    id: 'amex-gold-rewards',
    nameEn: 'Amex Gold Rewards Card',
    nameZh: '美国运通金卡',
    annualFee: 250,
    network: 'Amex',
    issuer: 'American Express',
    minIncome: 0,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { travel: 3, dining: 2, base: 1 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'travel',
    highlights: [
      '积分可转 Air Canada / British Airways 等多个航空',
      '旅行灵活性最强，积分不绑死一家航空',
      '机票 / 酒店 / 租车 3 倍积分',
    ],
    applyUrl: 'https://www.americanexpress.com/en-ca/credit-cards/gold-rewards-card/',
  },

  // ── E 类：高端卡 ─────────────────────────────────────────────────
  {
    id: 'wealthsimple-vip',
    nameEn: 'Wealthsimple Visa Infinite Privilege',
    nameZh: 'Wealthsimple Visa 无限特权卡',
    annualFee: 0,
    network: 'Visa',
    issuer: 'Wealthsimple',
    minIncome: 100000,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { base: 2 },
    noForeignFee: true,
    sobeysBonus: false,
    category: 'premium',
    highlights: [
      '所有消费 2% 返现，无上限无类别限制（包括房租）',
      '无外币手续费，海外消费也 2%',
      '最懒方案：什么都不用研究',
    ],
    applyUrl: 'https://www.wealthsimple.com/en-ca/credit-card',
  },
  {
    id: 'mbna-world-elite',
    nameEn: 'MBNA Rewards World Elite Mastercard',
    nameZh: 'MBNA 世界精英 Mastercard',
    annualFee: 120,
    network: 'Mastercard',
    issuer: 'MBNA',
    minIncome: 80000,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { groceries: 5, dining: 5, base: 1 },
    noForeignFee: false,
    sobeysBonus: false,
    category: 'premium',
    highlights: [
      '超市 + 餐厅 5 倍，积分可换现金 / 旅行 / 礼品卡',
      'Mastercard 网络，Costco 可用',
      '高消费人群性价比高',
    ],
    applyUrl: 'https://www.mbna.ca/en/credit-cards/rewards/mbna-rewards-world-elite-mastercard',
  },
  {
    id: 'scotia-platinum-amex',
    nameEn: 'Scotiabank Platinum American Express',
    nameZh: '丰业银行 Platinum Amex',
    annualFee: 399,
    network: 'Amex',
    issuer: 'Scotiabank',
    minIncome: 0,
    requiresCreditHistory: true,
    newcomerProgram: false,
    rewards: { base: 3 },
    noForeignFee: true,
    sobeysBonus: false,
    category: 'premium',
    highlights: [
      '14 次年度机场贵宾室，同类最多',
      '无外币手续费 + 低 9.99% 利率',
      '所有消费 3 倍 Scene+ 积分（注意：Costco 不接受 Amex）',
    ],
    applyUrl: 'https://www.scotiabank.com/ca/en/personal/credit-cards/american-express/platinum-card.html',
  },
]
